### ISSUE TITLE
Great to see this

### ISSUE THREAD

**Issue by retrogubbins** [rampa069/XZ-ESPectrum#1]
Fantastic, looks like you know what you're doing more than I did, will check this out rampa, Pete

**Comment by rampa069** [comment]
Hi pete. as an old spectrum hacker, i am enjoying this. I always wanted to do something like this, but didnt see clear until i saw your two cores code.

   There is a lot of improvement in the "z80emu" branch, check it please. I have changed lots of things (z80 emulator, snapshots, kempston joystick,Ay sound, ULA timings. osd with F1 key and starting to emulate +3) 

 If you need help with any of your fantastics emulators, tell mi and i'll be very glad to contribute!

**Comment by rampa069** [comment]
btw. are you the author of attribute2you demo? I am very interested in putting it in the SNA folder.

**Comment by jorgefuertes** [comment]
You both rulez!   
  
  
  
  
 Jorge Fuertes jorge@jorgefuertes.com http://jorgefuertes.com  

  
  
  
  
  
>

**Comment by retrogubbins** [comment]
Just been checking this out, looking really good! I only have a hacked together VGA socket directly onto the pins so the monitor is grossly overdriven, needs some serial resistors. I'm doing a new version of my PCB for LCD/SD/PS2/VGA, probably won't match BitLuni's pinouts though. Pete
