### ISSUE TITLE
How to compile ?

### ISSUE THREAD

**Issue by Zorglupy** [rampa069/XZ-ESPectrum#2]
Hello,

Would it be possible to have explanations on how to compile these sources (128k branch)? Is it a Platformio or Arduino project? Are there libraries that are not in these sources?

Thank you for this excellent project!

**Comment by jorgefuertes** [comment]
Hi, we are still at a dev stage but yes, you can compile osd or 128 branches, almost the same, with PlatformIO. You'll need a VROBER-B or delete "-DBOARD_HAS_PSRAM" define from your platformio.ini and use 48k arch only.

**Comment by Zorglupy** [comment]
Ok. When i try to compile imported files structure (from Github ZIP archive) with Platformio (or Arduino IDE) i have a lot errors concern include paths of .h files. Do you have some advice to solve this ?

**Comment by jorgefuertes** [comment]
Hummm... I'm sorry it compiles smoothly on my PlatformIO... Have you installed the "bitluni ESP32Lib"?

**Comment by Zorglupy** [comment]
Hmmmm, I'm a noob with Platformio ... so I opened the project in the wrong way ... I changed platformio.ini with my board (DOIT ESP32 Devkit) and removed "-DBOARD_HAS_PSRAM". I modified "hardware.h" with COLOUR_8. I need to push .rom files in SPIFFS. Can you give me the files/folders structure. I don't see it .... (may be in noota_3g.csv but not on Github ;-). Thx for your help !

**Comment by jorgefuertes** [comment]
Can you add me to telegram as @queru? Thanks.

**Comment by jorgefuertes** [comment]
Basically, you should make a 'data' dir in your project root and put this file as 'boot.cfg':

```
arch:48K
romset:SINCLAIR
ram:none
slog:true
wconn:false
```

Then the next structure:

```
rom
|_48K
  |_DIAG
    |_0.rom
  |_SE
    |_0.rom
  |_SINCLAIR
    |_0.rom
|_128K
  |_etc
sna
|_(Your .sna files)
```

**Comment by jorgefuertes** [comment]
Oh yes:

```
F1 - OSD MENU
F12 - Load next SNA
```

**Comment by Zorglupy** [comment]
Sorry, i'm not on Telegram.... I pushed the new files structure (Master branch worked well with Arduino IDE). Now, here is my terminal output :
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:9232
load:0x40080400,len:6412
entry 0x400806a8
Initalizing VGA
HEAP BEGIN 328436
E (51) SPIFFS: mount failed, -10025
[E][SPIFFS.cpp:52] begin(): Mounting SPIFFS failed! Error: -1
Cannot mount internal memory!
/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/freertos/queue.c:719 (xQueueGenericSend)- assert failed!
abort() was called at PC 0x4008ce23 on core 1

Backtrace: 0x400903d4:0x3ffb1e30 0x40090605:0x3ffb1e50 0x4008ce23:0x3ffb1e70 0x400d4469:0x3ffb1eb0 0x400d2d01:0x3ffb1ed0 0x400d2de2:0x3ffb1ef0 0x40080f3e:0x3ffb1f20 0x400d48fc:0x3ffb1f50 0x400db24f:0x3ffb1fb0 0x4008c5a1:0x3ffb1fd0

Rebooting...

It seems there is an issue with SPIFFS mount, because my board doesn't have PSRAM ?

**Comment by jorgefuertes** [comment]
No, PSRAM has nothing to do with FLASH, I have boards without PSRAM too and they works with 8b color or 16b and 48k arch. Maybe a bad formated FS or something... Please ensure the upload has been finished OK.

**Comment by rampa069** [comment]
are you sure you have uploaded the data to SPIFS? in platformio it us done with "run other task" and "PIO upload filesystem image" in arduino ide you need to install a plugin to do that (i think there are instructions in the main readme) Also have to format in the ide the filesystem in the tools menu leaving the max space to SPIFFS.

**Comment by rampa069** [comment]
in tools , partition scheme and "HUGE APP "

 this way you have 3mb free to roms and snapshots.

**Comment by Zorglupy** [comment]
Yeah ! It works ! I did not know how to upload to SPIFFS with Platformio ... and I did it with Arduino IDE.... Now it is Ok. Thanks for your help. I will soon receive a board with ESP32-WROVER and PSRAM to test the 128k version. I'll give you a feedback...
