### ISSUE TITLE
M5Stack support?

### ISSUE THREAD

**Issue by KodeMunkie** [rampa069/XZ-ESPectrum#3]
Any chance of M5Stack support (ESP32 based)? No VGA or PS2 port but built in 320x240 LCD screen, battery (+optional extender battery) GPIO, Bluetooth, WiFi.
I was thinking that you could get the LCD display working (M5.LCD functions) and either controlling by BT or, if not enough memory, directly wired buttons or keyboard into GPIO.
That could be a pretty nice portable spectrum :)

**Comment by jorgefuertes** [comment]
Hello Kode.
We don't have that board but we will take a look.
Thanks for interest.
