### ISSUE TITLE
Change from SPIFFS to SD card and get Guru meditation (loadprohibted)

### ISSUE THREAD

**Issue by fg1998** [rampa069/XZ-ESPectrum#4]
I´m trying to change all SPIFFS access to a SD Card on port 16. It looks like a very simple changes, and works great for 48k ROMS - boots and works OK. 
But loading SNA has a very strange behavior - works OK for fantasy.sna but none for other SNA (including Manic Minner what works on SPPIFS). Getting 'guru meditation errors' ater load_ram 

Some Log from COM

Some Help ?

-------------------------------CUT HERE----------------------------------------------------

Free heap after  Z80 RESET: 150656b
Loading ROMSET '/rom/48k/SINCLAIR'
Getting entries from: '/rom/48k/SINCLAIR'
Found FILE: /rom/48k/SINCLAIR/0.ROM...16384b...0.ROM...ADDING
Processing 1 ROMs
Loading file '/rom/48k/SINCLAIR/0.rom'
Loading ROM '/rom/48k/SINCLAIR/0.rom'
************** loadRam
Free heap before  SNA: 146012b
Loading file '/sna/manic.sna'
38
Free heap after  SNA: 146012
Ret address: 38 Stack: 7529 AF: 54 Border: 0 sna_size: 49179 rom: 1 bank: 0
*********** END LOAD RAM
End of setup
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400d969a  PS      : 0x00060130  A0      : 0x800d95bf  A1      : 0x3ffb1f30  
A2      : 0x00000038  A3      : 0x00000000  A4      : 0x3ffba8d8  A5      : 0x00000000  
A6      : 0x00000000  A7      : 0xff000000  A8      : 0x00000000  A9      : 0x3ffb1f10  
A10     : 0x0000084c  A11     : 0x00000000  A12     : 0x0000084c  A13     : 0x000075c0  
A14     : 0x00060320  A15     : 0x00000000  SAR     : 0x0000000a  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000038  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  

Backtrace: 0x400d969a:0x3ffb1f30 0x400d95bc:0x3ffb1f50 0x400d9a14:0x3ffb1f70 0x400d5168:0x3ffb1f90 0x400dd5b9:0x3ffb1fb0 0x4008d4c1:0x3ffb1fd0

Rebooting...

**Comment by jorgefuertes** [comment]
Hi Fernando.

As far as I remember we didn't tried it loading over SD, but it sounds to me as a lack of RAM problem, it may happen depend on the chip model, some mount less RAM.

Try to activate "#define COLOUR_8", it saves some RAM. You may deactivate some 128K model's banks too.

I'm sorry if don't help you too much, I have if a bit rust right now.

**Comment by jorgefuertes** [comment]
Wait, Fernando, my partner Rampa just called me and he believes he has another not yet uploaded branch with a complete SD support. He is doing an upload today.

**Comment by fg1998** [comment]
Thanks Jorge, it´s great to hear about a new branch with SD Support. Of course, don´t hesitate if you need some help from me.

It really looks RAM issue, but I had another ESP32 here to test, so I´ll do soon (and deactivate 128k modes) and other tests too.

Thanks for both of you for a great job on ESP32

Stay safe and health

**Comment by jorgefuertes** [comment]
Of course, pull requests are very welcome!

**Comment by fg1998** [comment]
Hi Folks ! Any news ?

**Comment by jorgefuertes** [comment]
I'm sorry, only @rampa069 seems to have the SD support on its local sources. I'll ask him again.

**Comment by abelykh0** [comment]
FYI, I created a pull request that uses SD on a VGA32 v1.4 board. You can get an idea from there. On this board the pins for the SD card reader are:
CS - 13, MOSI - 12, MISO - 2, CLK - 14.

**Comment by jorgefuertes** [comment]
Pull request merged.
