### ISSUE TITLE
Amstrad CPC support

### ISSUE THREAD

**Issue by WacKEDmaN** [rampa069/XZ-ESPectrum#5]
nice emulator, unfortunatly i dont use it much because i never had a speccy...
any thoughts of adding CPC support to this? the later speccy models where much the same right?

ive looked into coding my own emulator for cpc, but i dont have the coding skills!.. i dont know where to start!.. even after doing months of reading on the topic!

**Comment by jorgefuertes** [comment]
Hi @WacKEDmaN.

No, this emulator is staying as it is. Now we are in other projects, and my partner @rampa069 is more over FPGA things, like the Oric, Memotech, or CoCo cores.

I'm not sure if you can code a complete 6128 in this chip but sounds possible, not so different to Speccy. Unfortunately we aren't free now to help you.

Good luck!
